# Generated by Django 4.0.6 on 2022-08-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datos_familia',
            new_name='Datos',
        ),
    ]
